In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
x=pd.read_csv("matches.csv")
x

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,...,Match Report,NaN,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United
1385,39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,...,Match Report,NaN,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United
1386,40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,...,Match Report,NaN,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United
1387,41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,...,Match Report,NaN,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United
1388,42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,...,Match Report,NaN,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United

In [4]:
selected_fields = [
    'date', 
    'venue', 
    'result', 
    'gf', 
    'ga', 
    'opponent', 
    'xg', 
    'xga', 
    'poss', 
    'formation', 
    'sh', 
    'sot', 
    'dist', 
    'fk', 
    'pk', 
    'team'
]

# Create a new DataFrame with the selected fields
new_table = x[selected_fields]

# Save the new DataFrame to a new CSV file
new_table.to_csv('filtered_data.csv', index=False)

In [5]:
new_table

,date,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,dist,fk,pk,team
0,2021-08-15,Away,L,0.0,1.0,Tottenham,1.9,1.3,64.0,4-3-3,18.0,4.0,16.9,1.0,0.0,Manchester City
1,2021-08-21,Home,W,5.0,0.0,Norwich City,2.7,0.1,67.0,4-3-3,16.0,4.0,17.3,1.0,0.0,Manchester City
2,2021-08-28,Home,W,5.0,0.0,Arsenal,3.8,0.1,80.0,4-3-3,25.0,10.0,14.3,0.0,0.0,Manchester City
3,2021-09-11,Away,W,1.0,0.0,Leicester City,2.9,0.8,61.0,4-3-3,25.0,8.0,14.0,0.0,0.0,Manchester City
4,2021-09-18,Home,D,0.0,0.0,Southampton,1.1,0.4,63.0,4-3-3,16.0,1.0,15.7,1.0,0.0,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,2021-05-02,Away,L,0.0,4.0,Tottenham,0.5,2.0,34.0,3-4-1-2,8.0,1.0,17.4,0.0,0.0,Sheffield United
1385,2021-05-08,Home,L,0.0,2.0,Crystal Palace,0.7,2.1,50.0,3-5-2,7.0,0.0,11.4,1.0,0.0,Sheffield United
1386,2021-05-16,Away,W,1.0,0.0,Everton,1.6,1.3,38.0,3-4-3,10.0,3.0,17.0,0.0,0.0,Sheffield United
1387,2021-05-19,Away,L,0.0,1.0,Newcastle Utd,0.8,1.5,50.0,3-4-3,11.0,1.0,16.0,1.0,0.0,Sheffield United
1388,2021-05-23,Home,W,1.0,0.0,Burnley,0.6,1.0,41.0,3-4-3,12.0,3.0,17.0,0.0,0.0,Sheffield United

In [6]:
new_table.dtypes

date          object
venue         object
result        object
gf           float64
ga           float64
opponent      object
xg           float64
xga          float64
poss         float64
formation     object
sh           float64
sot          float64
dist         float64
fk           float64
pk           float64
team          object
dtype: object

In [7]:
# Example: Check rows where 'gf' or 'xg' is NaN
missing_specific = new_table[new_table['dist'].isna()]
print(missing_specific)

            date venue result   gf   ga  opponent   xg  xga  poss formation  \
1127  2020-10-18  Home      D  1.0  1.0  Brighton  0.8  1.1  34.0     4-4-2

       sh  sot  dist   fk   pk            team
1127  0.0  0.0   NaN  0.0  1.0  Crystal Palace

In [8]:
new_table['dist'] = new_table['dist'].fillna(25)

print(new_table.loc[1127])  # Verify the update for the specific row

date             2020-10-18
venue                  Home
result                    D
gf                      1.0
ga                      1.0
opponent           Brighton
xg                      0.8
xga                     1.1
poss                   34.0
formation             4-4-2
sh                      0.0
sot                     0.0
dist                   25.0
fk                      0.0
pk                      1.0
team         Crystal Palace
Name: 1127, dtype: object

C:\Users\HP\AppData\Local\Temp\ipykernel_3056\4121539467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_table['dist'] = new_table['dist'].fillna(25)

In [9]:
new_table.isna().sum()

date         0
venue        0
result       0
gf           0
ga           0
opponent     0
xg           0
xga          0
poss         0
formation    0
sh           0
sot          0
dist         0
fk           0
pk           0
team         0
dtype: int64

In [10]:
new_table.head(2)

,date,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,dist,fk,pk,team
0,2021-08-15,Away,L,0.0,1.0,Tottenham,1.9,1.3,64.0,4-3-3,18.0,4.0,16.9,1.0,0.0,Manchester City
1,2021-08-21,Home,W,5.0,0.0,Norwich City,2.7,0.1,67.0,4-3-3,16.0,4.0,17.3,1.0,0.0,Manchester City

In [11]:
#win and loss
table1=new_table[['venue','result','team','opponent']]
table1

     venue result              team        opponent
0     Away      L   Manchester City       Tottenham
1     Home      W   Manchester City    Norwich City
2     Home      W   Manchester City         Arsenal
3     Away      W   Manchester City  Leicester City
4     Home      D   Manchester City     Southampton
...    ...    ...               ...             ...
1384  Away      L  Sheffield United       Tottenham
1385  Home      L  Sheffield United  Crystal Palace
1386  Away      W  Sheffield United         Everton
1387  Away      L  Sheffield United   Newcastle Utd
1388  Home      W  Sheffield United         Burnley

[1389 rows x 4 columns]

In [48]:
dummies=pd.get_dummies(table1[['result','team','opponent']])

In [51]:
merged_table1=pd.concat([table1,dummies],axis=1)

In [52]:
merged_table1

,venue,result,team,opponent,result_0,result_1,result_2,team_0,team_1,team_2,...,opponent_13,opponent_14,opponent_15,opponent_16,opponent_17,opponent_18,opponent_19,opponent_20,opponent_21,opponent_22
0,0,1,12,18,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,1,2,12,15,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,1,2,12,0,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0,2,12,10,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1,0,12,17,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0,1,16,18,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1385,1,1,16,6,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1386,0,2,16,7,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1387,0,1,16,14,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1388,1,2,16,4,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [61]:
merge=merged_table1.drop('result',axis=1)

In [62]:
ydata=merged_table1.result

In [63]:
merge

,venue,team,opponent,result_0,result_1,result_2,team_0,team_1,team_2,team_3,...,opponent_13,opponent_14,opponent_15,opponent_16,opponent_17,opponent_18,opponent_19,opponent_20,opponent_21,opponent_22
0,0,12,18,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,1,12,15,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,1,12,0,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0,12,10,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1,12,17,True,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0,16,18,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1385,1,16,6,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1386,0,16,7,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1387,0,16,14,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1388,1,16,4,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [64]:
ydata

0       1
1       2
2       2
3       2
4       0
       ..
1384    1
1385    1
1386    2
1387    1
1388    2
Name: result, Length: 1389, dtype: object

In [84]:
ydata=pd.cut(ydata,bins=3,labels=['loss','wins','draw'])

In [124]:
ydata[0:5]

0    wins
1    draw
2    draw
3    draw
4    loss
Name: result, dtype: category
Categories (3, object): ['loss' < 'wins' < 'draw']

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
from sklearn.linear_model import LogisticRegression

In [72]:
modellogistic=LogisticRegression()

In [75]:
X_train.shape

(972, 3)

In [85]:
X_train,xtest,Y_train,ytest=train_test_split(merge[['venue','team','opponent']],ydata,test_size=.3)

In [86]:
X_train.shape

(972, 3)

In [87]:
Y_train.shape

(972,)

In [88]:
xtest.shape

(417, 3)

In [89]:
modellogistic.fit(X_train,Y_train)

LogisticRegression()

In [91]:
modellogistic.score(xtest,ytest)

0.38609112709832133

In [90]:
modellogistic.predict(xtest)

array(['wins', 'draw', 'wins', 'wins', 'wins', 'draw', 'wins', 'draw',
       'wins', 'wins', 'draw', 'draw', 'wins', 'wins', 'draw', 'wins',
       'draw', 'wins', 'wins', 'draw', 'draw', 'draw', 'draw', 'wins',
       'draw', 'wins', 'wins', 'draw', 'wins', 'wins', 'wins', 'wins',
       'wins', 'wins', 'wins', 'draw', 'wins', 'wins', 'wins', 'wins',
       'wins', 'wins', 'draw', 'draw', 'wins', 'draw', 'draw', 'wins',
       'wins', 'wins', 'wins', 'wins', 'wins', 'draw', 'wins', 'draw',
       'draw', 'wins', 'draw', 'draw', 'wins', 'draw', 'wins', 'draw',
       'draw', 'wins', 'wins', 'draw', 'wins', 'wins', 'draw', 'draw',
       'draw', 'draw', 'wins', 'draw', 'draw', 'draw', 'draw', 'wins',
       'wins', 'wins', 'wins', 'draw', 'draw', 'wins', 'draw', 'wins',
       'wins', 'wins', 'draw', 'wins', 'draw', 'draw', 'draw', 'wins',
       'draw', 'draw', 'wins', 'draw', 'draw', 'draw', 'wins', 'wins',
       'wins', 'wins', 'wins', 'wins', 'draw', 'wins', 'wins', 'wins',
       'draw', 'wins', 'draw', 'wins', 'wins', 'wins', 'draw', 'wins',
       'wins', 'wins', 'wins', 'wins', 'wins', 'wins', 'wins', 'wins',
       'wins', 'draw', 'wins', 'draw', 'wins', 'draw', 'wins', 'wins',
       'wins', 'draw', 'draw', 'wins', 'wins', 'wins', 'wins', 'draw',
       'draw', 'draw', 'wins', 'wins', 'draw', 'draw', 'wins', 'wins',
       'draw', 'draw', 'wins', 'draw', 'wins', 'draw', 'draw', 'draw',
       'wins', 'wins', 'draw', 'draw', 'wins', 'wins', 'draw', 'draw',
       'wins', 'draw', 'wins', 'draw', 'wins', 'wins', 'wins', 'wins',
       'draw', 'wins', 'wins', 'wins', 'draw', 'wins', 'wins', 'wins',
       'wins', 'wins', 'draw', 'draw', 'wins', 'draw', 'wins', 'wins',
       'wins', 'wins', 'wins', 'draw', 'wins', 'wins', 'wins', 'draw',
       'wins', 'wins', 'wins', 'wins', 'draw', 'wins', 'draw', 'wins',
       'draw', 'wins', 'wins', 'draw', 'draw', 'draw', 'draw', 'draw',
       'draw', 'draw', 'wins', 'draw', 'wins', 'draw', 'wins', 'wins',
       'wins', 'draw', 'wins', 'draw', 'wins', 'draw', 'draw', 'wins',
       'wins', 'wins', 'draw', 'wins', 'draw', 'draw', 'wins', 'draw',
       'wins', 'draw', 'wins', 'draw', 'draw', 'draw', 'wins', 'draw',
       'draw', 'wins', 'draw', 'draw', 'draw', 'draw', 'draw', 'draw',
       'draw', 'wins', 'wins', 'draw', 'draw', 'draw', 'wins', 'wins',
       'draw', 'draw', 'wins', 'wins', 'wins', 'draw', 'wins', 'draw',
       'wins', 'draw', 'wins', 'draw', 'wins', 'wins', 'wins', 'wins',
       'wins', 'wins', 'draw', 'wins', 'wins', 'draw', 'wins', 'draw',
       'wins', 'draw', 'wins', 'wins', 'draw', 'draw', 'draw', 'wins',
       'wins', 'wins', 'draw', 'wins', 'wins', 'wins', 'wins', 'draw',
       'wins', 'draw', 'wins', 'draw', 'wins', 'wins', 'wins', 'wins',
       'wins', 'draw', 'wins', 'wins', 'wins', 'draw', 'draw', 'draw',
       'wins', 'draw', 'draw', 'wins', 'wins', 'wins', 'draw', 'wins',
       'draw', 'draw', 'wins', 'wins', 'draw', 'wins', 'wins', 'wins',
       'draw', 'wins', 'wins', 'wins', 'draw', 'draw', 'draw', 'wins',
       'draw', 'wins', 'wins', 'draw', 'wins', 'wins', 'draw', 'draw',
       'draw', 'draw', 'wins', 'wins', 'wins', 'draw', 'wins', 'draw',
       'wins', 'wins', 'draw', 'draw', 'draw', 'wins', 'draw', 'draw',
       'wins', 'wins', 'wins', 'wins', 'wins', 'draw', 'draw', 'draw',
       'wins', 'wins', 'wins', 'wins', 'draw', 'draw', 'draw', 'wins',
       'draw', 'draw', 'wins', 'wins', 'wins', 'wins', 'draw', 'wins',
       'draw', 'draw', 'wins', 'wins', 'wins', 'draw', 'draw', 'wins',
       'draw', 'draw', 'wins', 'draw', 'draw', 'draw', 'draw', 'draw',
       'wins', 'wins', 'draw', 'wins', 'wins', 'wins', 'draw', 'draw',
       'draw'], dtype=object)

In [94]:
merged_table1.iloc[1384]

venue              0
result             1
team              16
opponent          18
result_0       False
result_1        True
result_2       False
team_0         False
team_1         False
team_2         False
team_3         False
team_4         False
team_5         False
team_6         False
team_7         False
team_8         False
team_9         False
team_10        False
team_11        False
team_12        False
team_13        False
team_14        False
team_15        False
team_16         True
team_17        False
team_18        False
team_19        False
team_20        False
team_21        False
team_22        False
opponent_0     False
opponent_1     False
opponent_2     False
opponent_3     False
opponent_4     False
opponent_5     False
opponent_6     False
opponent_7     False
opponent_8     False
opponent_9     False
opponent_10    False
opponent_11    False
opponent_12    False
opponent_13    False
opponent_14    False
opponent_15    False
opponent_16    False
opponent_17    False
opponent_18     True
opponent_19    False
opponent_20    False
opponent_21    False
opponent_22    False
Name: 1384, dtype: object

In [95]:
modellogistic.predict([[0,16,18]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['wins'], dtype=object)

In [96]:
from sklearn.model_selection import cross_val_score

In [98]:
logisticvl=cross_val_score(LogisticRegression(),merge[['venue','team','opponent']],ydata)

In [99]:
logisticvl

array([0.41366906, 0.34172662, 0.35611511, 0.38848921, 0.39711191])

In [100]:
logisticvl.mean()

0.3794223826714801

In [101]:
from sklearn.svm import SVC

In [102]:
Svcvl=cross_val_score(SVC(),merge[['venue','team','opponent']],ydata)

In [103]:
Svcvl

array([0.37769784, 0.3705036 , 0.40647482, 0.38489209, 0.38628159])

In [104]:
Svcvl.mean()

0.3851699867542789

In [105]:
from sklearn.ensemble import RandomForestClassifier

In [106]:
RFvl=cross_val_score(RandomForestClassifier(),merge[['venue','team','opponent']],ydata)

In [107]:
RFvl

array([0.4352518 , 0.31654676, 0.46043165, 0.35971223, 0.37545126])

In [108]:
RFvl.mean()

0.38947874191621434

In [109]:
from sklearn import tree

In [110]:
DTvl=cross_val_score(tree.DecisionTreeClassifier(),merge[['venue','team','opponent']],ydata)

In [111]:
DTvl

array([0.42446043, 0.33453237, 0.43165468, 0.35611511, 0.35018051])

In [112]:
DTvl.mean()

0.37938861906864396

In [113]:
#randomforestclassifier
rfmodel=RandomForestClassifier()

In [114]:
rfmodel.fit(X_train,Y_train)

RandomForestClassifier()

In [115]:
rfmodel.score(xtest,ytest)

0.39568345323741005

In [127]:
#model saving
import joblib

In [119]:
joblib.dump(rfmodel,'winning-result')

['winning-result']

In [128]:
#model loading and checking
n=joblib.load('winning-result')

In [126]:
n.predict([[0,16,18]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['wins'], dtype=object)